#!/usr/bin/env python

#Given a PLANET field name, with a very free form definition, it will load
#the template FITS file into a (previously started) running copy of SAOtng
#or SAO ds9, and highlight and label the microlens and all reference
#stars. The argument is very flexible - 'eb2k05', 'WEB2K005I', 'wEB2K05i', etc
#are all valid. If the filter is left out, it defaults to I.

#Local customisation:
#Note - these lines override the definitions in the planet.py, improc.py and
#xpa.py modules. If you are using these modules seperately, duplicate the
#changes in the configuration sections in each module.

#Uncomment one of these two lines depending on which image viewer you use,
#SAOimage tng or SAOimage ds9. The original SAOimage and Ximtool don't support
#The X Public Access Mechanism to control them remotely - and are also vastly
#inferior. I highly recommend swapping to one of these two image viewers, they
#Are backwards compatible with both SAOimage and Ximtool.
#

viewer='ds9'
#viewer='SAOtng'

#Uncomment one of these two lines depending on whether your site uses the OSU
#directory tree model (a base directory, then a subdirectory for each object,
#then Work, Archive, etc under that) or the original pipeline directory tree
#(a base, then one shared ARCHIVE directory, one shared WORK directory, etc).
#
#The code is set up for our local model - OSU format, with a base directory,
#A year directory (2KSeason, etc) then an object directory. Edit the planet.py
#file to make any changes, at the start and inside the Pobject class.
#
#Currently, with OSUpipe=1 it will look for:
#  eb2k05    as   PipeHome+'/2KSeason/EB2K05/Archive/WEB2K005I'
#With OSUpipe=0 it will look for:
#  eb2k05    in   PipeHome+'/ARCHIVE/WEB2K005I'

#OSUpipe=1
OSUpipe=0

#Set the base pipeline directory here:

PipeHome='/home/observer'

#Set the local site letter here:

site='W'

#**********************************************************
#        End of local customisation                       *
#**********************************************************

import sys
import xpa
import planet
import improc

xpa.viewer=viewer
improc.viewer=viewer
planet.viewer=viewer
planet.site=site
planet.PipeHome=PipeHome
planet.OSUpipe=OSUpipe

planet.showrefs(sys.argv[1])
