#!/usr/bin/python

import sys
sys.path.append('/home/observer/bin/prosp2')

import objects
import string
import cgi

form = cgi.FieldStorage()

def tryget(n):
  try:
    tmp=form[n].value
  except:
    tmp=""
  return tmp

def trygetfloat(n):
  try:
    tmp=float(form[n].value)
  except:
    tmp=0.0
  return tmp

new=tryget("new")
save=tryget("save")
saveyes=tryget("saveyes")
delete=tryget("delete")
delyes=tryget("delyes")

ObjID=string.upper(tryget("ObjID"))
ObjRA=tryget("ObjRA")
ObjDec=tryget("ObjDec")
ObjEpoch=trygetfloat("ObjEpoch")
filtname=tryget("filtname")
exptime=trygetfloat("exptime")
xg=int(trygetfloat("xg"))
yg=int(trygetfloat("yg"))
type=string.upper(tryget("type"))
period=trygetfloat("period")
name=tryget("Name")
comment=tryget("comment")

if not ObjID:
  ObjID="newobj"

ob=objects.Object(ObjID)
if save or saveyes or new:
  ob.ObjRA=ObjRA
  ob.ObjDec=ObjDec
  ob.ObjEpoch=ObjEpoch
  ob.filtname=filtname
  ob.exptime=exptime
  ob.XYpos=(xg,yg)
  ob.type=type
  ob.period=period
  ob.name=name
  ob.comment=comment


def trow(s):
  return "<tr> "+s+"</tr>\n"

def head(s):
  return "<th> "+s+"</th>"

def data(s):
  if s:
    return "<td>"+s+"</td>"
  else:
    return "<td>&nbsp;</td>"

def tfield(n,s,l):
  return '<INPUT TYPE=TEXT NAME="'+n+'" SIZE='+`l`+' VALUE="'+s+'">'

def Form(script='objedit',content=''):
  return '<FORM METHOD="POST" ACTION="'+script+'">\n\n'+ \
         content+'</FORM>'

def EditTable(ob=None):
  tmp="<table border=1>"
  tmp=tmp+trow(head("ObjID")+
             data(tfield("ObjID",ob.ObjID,14)))
  tmp=tmp+trow(head("Name")+
             data(tfield("Name",ob.name,30)))
  tmp=tmp+trow(head("ObjRA")+
             data(tfield("ObjRA",ob.ObjRA,14)))
  tmp=tmp+trow(head("ObjDec")+
             data(tfield("ObjDec",ob.ObjDec,14)))
  tmp=tmp+trow(head("ObjEpoch")+
             data(tfield("ObjEpoch",str(ob.ObjEpoch),14)))
  tmp=tmp+trow(head("Filter")+
             data(tfield("filtname",ob.filtname,8)))
  tmp=tmp+trow(head("Exp.Time")+
             data(tfield("exptime",str(ob.exptime),8)))
  tmp=tmp+trow(head("XYpos")+
             data(tfield("xg",`ob.XYpos[0]`,5)+","+
                  tfield("yg",`ob.XYpos[1]`,5)))
  tmp=tmp+trow(head("Type")+
             data(tfield("type",ob.type,8)))
  tmp=tmp+trow(head("Period")+
             data(tfield("period",str(ob.period),8)))
  tmp=tmp+trow(head("Comment")+
             data(tfield("comment",ob.comment,80)))
  tmp=tmp+"</table>\n<BR>\n"

  return tmp


def hfield(n,s):
  return '<INPUT TYPE=HIDDEN NAME="'+n+'" VALUE="'+s+'">'

def ConfirmTable(ob=None):
  tmp=hfield("ObjID",ob.ObjID)+"\n"
  tmp=tmp+hfield("Name",ob.name)+"\n"
  tmp=tmp+hfield("ObjRA",ob.ObjRA)+"\n"
  tmp=tmp+hfield("ObjDec",ob.ObjDec)+"\n"
  tmp=tmp+hfield("ObjEpoch",str(ob.ObjEpoch))+"\n"
  tmp=tmp+hfield("filtname",ob.filtname)+"\n"
  tmp=tmp+hfield("exptime",str(ob.exptime))+"\n"
  tmp=tmp+hfield("xg",`ob.XYpos[0]`)+"\n"
  tmp=tmp+hfield("yg",`ob.XYpos[1]`)+"\n"
  tmp=tmp+hfield("type",ob.type)+"\n"
  tmp=tmp+hfield("period",str(ob.period))+"\n"
  tmp=tmp+hfield("comment",ob.comment)+"\n"

  tmp=tmp+"<table border=1>"
  tmp=tmp+trow(head("ObjID")+
             data(ob.ObjID))
  tmp=tmp+trow(head("Name")+
             data(ob.name))
  tmp=tmp+trow(head("ObjRA")+
             data(ob.ObjRA))
  tmp=tmp+trow(head("ObjDec")+
             data(ob.ObjDec))
  tmp=tmp+trow(head("ObjEpoch")+
             data(str(ob.ObjEpoch)))
  tmp=tmp+trow(head("Filter")+
             data(ob.filtname))
  tmp=tmp+trow(head("Exp.Time")+
             data(str(ob.exptime)))
  tmp=tmp+trow(head("XYpos")+
             data(`ob.XYpos[0]`+","+
                  `ob.XYpos[1]`))
  tmp=tmp+trow(head("Type")+
             data(ob.type))
  tmp=tmp+trow(head("Period")+
            data(str(ob.period)))
  tmp=tmp+trow(head("Comment")+
             data(ob.comment))
  tmp=tmp+"</table>\n<BR>\n"

  return tmp


def DisplayDone():
  print '<P>Go to <A href="../al/aobjlist">Objects Database</A>, or <P>\n'+ \
       '<A href="../platstat">Observing Status Page</A>.<P>'


#
#Begin text output:
#

print "Content-Type: text/html\n\n"

print "<html>\n\n"

print "<title>Object "+ob.ObjID+"</title>\n"

print "<h1>Object "+ob.ObjID+"</h1>\n"

if new or ((not save) and (not saveyes) and (not delete) and (not delyes)):
  print Form(script='objedit',
             content=EditTable(ob)+
                     '<INPUT TYPE=SUBMIT NAME="save" VALUE="Save Changes">'+
                     '<BR>or<BR>'
                     '<INPUT TYPE=SUBMIT NAME="delete" VALUE="Delete Object">')
elif save or saveyes:
  if save:
    result=ob.save(ask=0,force=0)
    if not result:
      print Form(script='objedit',
                 content=ConfirmTable(ob)+
                         "Are you sure you want to overwrite this object?"+
                         '<P>\n <INPUT TYPE=SUBMIT NAME="saveyes" '+
                         'VALUE="Yes, Save Object">\n')
  elif saveyes:
    result=ob.save(ask=0,force=1)
    if not result:
      print "<H1>Save Failed!!!!</H1><P>\n\n"
elif delete or delyes:
  if delete:
    print Form(script='objedit',
            content=ConfirmTable(ob)+
               "<H2>Are you SURE you want to <B>DELETE</B> this object?</H2>"+
               '<P>\n<INPUT TYPE=SUBMIT NAME="delyes" '+
               ' VALUE="Yes, Delete Object">\n')
  elif delyes:
    result=ob.delete(ask=0)
    if not result:
      print "<H1>Delete Failed!!!!</H1><P>\n\n"

DisplayDone()
 
print "</html>"


